org.gradle.jvmargs=-Xmx6G
org.gradle.daemon=false

platforms=fabric,neoforge

minecraft_version=26.1.2
supported_version=26.1.2
forge_minecraft_version=26.1.2

artifact_type=release

archives_base_name=architectury
archives_base_name_snapshot=architectury-snapshot
base_version=20.0.0-aleph.1
maven_group=dev.architectury
version_suffix=

fabric_loader_version=0.18.5
fabric_api_version=0.145.4+26.1.2
mod_menu_version=18.0.0-alpha.5

forge_version=64.0.8
neoforge_version=26.1.2.41-beta

# Set to empty if not snapshots
neoforge_pr=

curseforge_id=419699
modrinth_id=lhGA9TYQ

loom.ignoreDependencyLoomVersionValidation=true
loom.allowMismatchedPlatformVersion=true
